AWSTemplateFormatVersion: '2010-09-09'

Description: prophase-bot-service stack

Parameters:
  Env:
    Description: Environment prefix
    Type: String
  ServiceName:
    Description: Name of bot impl service
    Type: String
  DefaultSecurityGroup:
    Description: DefaultSecurityGroup
    Type: String
  Subnet01Id:
    Description: VPC Subnet01
    Type: String
  Subnet02Id:
    Description: VPC Subnet01
    Type: String

Resources:
  ServiceRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: prophase-bot-service
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowPushPull
            Effect: Allow
            Principal:
              AWS:
                - "arn:aws:iam::149284612295:user/GitHub_Actions"
            Action:
              - "ecr:*"
