AWSTemplateFormatVersion: '2010-09-09'

Description: Prophase Bot Service stack

Parameters:
  ServiceName:
    Description: Name of the service
    Type: String

Resources:
  ServiceRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub ${ServiceName}
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowPushPull
            Effect: Allow
            Principal:
              AWS:
                - "arn:aws:iam::149284612295:user/GitHub_Actions"
            Action:
              - "ecr:*"