AWSTemplateFormatVersion: '2010-09-09'

Description: Prophase infrastructure stack

Parameters:
  Env:
    Description: Environment prefix
    Type: String
  BotServiceName:
    Description: Name of bot impl service
    Type: String

Resources:
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub ${Env}-vpc
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${Env} VPC Internet Gateway
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway
  Subnet01:
    Type: 'AWS::EC2::Subnet'
    Properties:
      CidrBlock: 10.0.96.0/19
      AvailabilityZone: !Select
        - '0'
        - !GetAZs
          Ref: 'AWS::Region'
      VpcId: !Ref VPC
  Subnet02:
    Type: 'AWS::EC2::Subnet'
    Properties:
      CidrBlock: 10.0.128.0/19
      AvailabilityZone: !Select
        - '1'
        - !GetAZs
          Ref: 'AWS::Region'
      VpcId: !Ref VPC


#####################################
#               API                 #
#####################################
  RestApi:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      EndpointConfiguration:
        Types:
          - EDGE
      Name: !Sub ${Env}-api

#  RestApiDeployment:
#    Type: AWS::ApiGateway::Deployment
#    DependsOn:
#      - PostBotMethod
#    Properties:
#      RestApiId: !Ref RestApi

#  RestApiStage:
#    Type: AWS::ApiGateway::Stage
#    Properties:
#      StageName: !Sub ${Env}
#      Description: !Sub ${Env} Stage
#      RestApiId: !Ref RestApi
#      DeploymentId: !Ref RestApiDeployment

  RestApiRootResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt RestApi.RootResourceId
      PathPart: api
      RestApiId: !Ref RestApi

# Api Methods Level 1
  PostBotMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: POST
#      Integration:
#        ConnectionType: INTERNET
#        IntegrationHttpMethod: POST
#        Type: AWS_PROXY
      ResourceId: !Ref RestApiRootResource
      RestApiId: !Ref RestApi


#####################################
#             CLUSTER               #
#####################################
  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Description: Role to execute ACS Task

  ECSCluster:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName: !Sub ${Env}

Outputs: {}