name: 'Deploy to AWS CloudFormation'

on:
  push:
    branches:
      - develop
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Sen prod env
        if: ( github.ref == 'main' )
        id: values
        run: |
              echo "::set-output name=env::prod"
      - name: Sen dev env
        if: ( github.ref != 'main' )
        id: values
        run: |
          echo "::set-output name=env::dev"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}
          aws-region: ${{ variables.AWS_REGION }}

      - name: Deploy AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ steps.values.outputs.env }}-${{ variables.SERVICE_NAME }}
          template: prophase-bot.yaml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: BotServiceName=${{ variables.SERVICE_NAME }}
