name: 'Deploy AWS CloudFormation'

on:
  push:
    branches:
      - develop
      - main
  workflow_dispatch:
  pull_request:

env:
  env-name: dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set prod env
        if: ( github.ref == 'main' )
        run: |
          echo "env-name=prod" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Upload templates to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ vars.AWS_TEMPLATES_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          SOURCE_DIR: "templates"