name: 'Deploy AWS CloudFormation'

on:
  push:
    branches:
      - develop
      - main
  workflow_dispatch:
  pull_request:

env:
  env-name: dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set prod env
        if: ( github.ref == 'main' )
        run: |
          echo "env-name=prod" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Upload templates to S3
        run: |
          aws s3 cp ./templates s3://149284612295/dev/cf-templates/ --recursive

      - name: Deploy AWS CloudFormation Stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ env.env-name }}-prophase
          template: s3://149284612295/dev/cf-templates/infrastructure.yaml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: >-
            Env=${{ env.env-name }}