name: 'Deploy to AWS CloudFormation'

on:
  push:
    branches:
      - develop
      - main
  workflow_dispatch:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Sen prod env
        if: ( github.ref == 'main' )
        run: |
          echo "env-name=prod" >> $GITHUB_ENV
      - name: Sen dev env
        if: ( github.ref != 'main' )
        run: |
          echo "env-name=dev" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ env.env-name }}-${{ env.SERVICE_NAME }}
          template: prophase-bot.yaml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: BotServiceName=${{ env.SERVICE_NAME }}
